/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication6;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author jafar
 */
public class Ändralösenordföragenochalien extends javax.swing.JFrame {
private static InfDB idb;




 public ArrayList<String> agentallpassword;
   public  ArrayList<String> alienallpassword;






    /**
     * Creates new form Ändralösenordföragenochalien
     */
   
   // detta är konstruktor för klassen ändralösenordföragenochalien //
    public Ändralösenordföragenochalien( ) {
      
        
        
            try {
           idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            
        }
        initComponents();
        agentallpassword= new ArrayList<String> ();
        alienallpassword= new ArrayList<String> (); 
        gettinglösenorden();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    // jag användar den här methode för att hämta lösenorden och spara dem i arraylisten, därför skapade jag arraylisten 
    public void gettinglösenorden(){
     
      
         
    try { 
        agentallpassword=idb.fetchColumn("SELECT LOSENORD FROM AGENT;");
        alienallpassword=idb.fetchColumn("SELECT LOSENORD FROM ALIEN;");
        
    } catch (InfException ex) {
        Logger.getLogger(Ändralösenordföragenochalien.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println(" Något gick fel när sytemet försökte hämta lösenorden");
         
    }
        
    }
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nyttlösenord = new javax.swing.JTextField();
        Gammallösenord = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Lösennordshantering för agent och alien ");

        jLabel2.setText("Nytt Lösenord:");

        jLabel3.setText("Föregående lösenord:");

        jButton1.setText("Ändra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Nyttlösenord, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gammallösenord, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nyttlösenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gammallösenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// här ska jag coda knappen för att ändra lösenorden 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String newpasscode= Nyttlösenord.getText();
        String oldpasscode= Gammallösenord.getText(); 
        
        // här uppdeteteras lösenorden för agent och alien om det gamla lösenordet stämmer rätt.
        
    
        boolean findoldpasswordforagent=false; 
        boolean findoldpasswordforalien=false; 
                      
             for ( String pass: agentallpassword){
                 if( pass.equals(oldpasscode)){
                     findoldpasswordforagent=true; 
                     
                 }
             }
             
             
             if( findoldpasswordforagent=true)
              try {
             
             
             idb.update("UPDATE agent SET losenord = " + "'" + newpasscode + "'" + " WHERE losenord = " + "'" + oldpasscode + "'");
                           System.out.println(" Lösenordet har ändrats! ");
                            JOptionPane.showMessageDialog(null, " Du har ändrat ditt lösenord och ditt nya lösenord är "+newpasscode);
                            } 
                            catch (InfException ettUndantag) {
                                JOptionPane.showMessageDialog(null, "Någonting gick fel");
                            System.out.println(" Något gick fel, vänligen försök igen");
                            } 
        
        
        
         for ( String alienpass: alienallpassword){   // här måste man loopa genom gamla lösenord och säkerställer att de finns
                 if( alienpass.equals(oldpasscode)){
                     findoldpasswordforalien=true; 
                     
                 }
             }
             
             
             if( findoldpasswordforalien=true)
              try {
             
             
             idb.update("UPDATE alien SET losenord = " + "'" + newpasscode + "'" + " WHERE losenord = " + "'" + oldpasscode + "'");
                           System.out.println(" Lösenordet har ändrats!");
                            JOptionPane.showMessageDialog(null, " Ditt nya lösenord är "+newpasscode);
                            } 
                            catch (InfException ettUndantag) {
                                JOptionPane.showMessageDialog(null, "Någnting gick fel");
                            System.out.println(" Något gick fel, vänligen försök igen");
                            } 
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ändralösenordföragenochalien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ändralösenordföragenochalien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ändralösenordföragenochalien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ändralösenordföragenochalien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
             new Ändralösenordföragenochalien().setVisible(true);
            }
       });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Gammallösenord;
    private javax.swing.JTextField Nyttlösenord;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
